/* database creation*/
CREATE DATABASE IF NOT EXISTS WALK_IN_PORTAL;
/* use database*/
USE WALK_IN_PORTAL;

/* users table : userid,profilepic,firstname,lastname,email,mobileno,resumepath,portfolio_url,refferal,updates_via_mail,password_hash*/
CREATE TABLE IF NOT EXISTS USERS(
USER_ID INT AUTO_INCREMENT PRIMARY KEY,
PROFILE_PICTURE VARCHAR(100),
FIRST_NAME VARCHAR(100),
LAST_NAME VARCHAR(100),
EMAIL VARCHAR(100),
MOBILE_NO VARCHAR(15),
RESUME_PATH VARCHAR(255),
PORTFOLIO_URL VARCHAR(255),
REFFERAL VARCHAR(100),
UPDATES_VIA_MAIL ENUM('0', '1'),
PASSWORD_HASH VARCHAR(100) NOT NULL
);


CREATE TABLE IF NOT EXISTS JOB_ROLES(
ROLE_ID INT AUTO_INCREMENT PRIMARY KEY,
ROLE_NAME VARCHAR(100) NOT NULL
);


CREATE TABLE IF NOT EXISTS USER_JOB_ROLES(
USER_ID INT,
ROLE_ID INT,
PRIMARY KEY (USER_ID,ROLE_ID),
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
FOREIGN KEY (ROLE_ID) REFERENCES JOB_ROLES(ROLE_ID)
);

CREATE TABLE IF NOT EXISTS USER_EDUCATION_QUALIFICATIONS(
USER_ID INT PRIMARY KEY,
AGGREGATE_PERCENTAGE INT,
PASSING_YEAR INT,
QUALIFICATION VARCHAR(100),
STREAM_NAME VARCHAR(100),
COLLEGE VARCHAR(100),
COLLEGE_LOCATION VARCHAR(100),
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE IF NOT EXISTS USER_PROFESSIONAL_QUALIFICATIONS(
USER_ID INT PRIMARY KEY,
APPLICANT_TYPE VARCHAR(20) NOT NULL CHECK (APPLICANT_TYPE IN ('FRESHER', 'EXPERIENCED')),
EXPERIENCE INT,
CURRENT_CTC INT,
EXPECTED_CTC INT,
NOTICE_PERIOD ENUM('0', '1'),
NOTICE_PERIOD_END DATE,
NOTICE_PERIOD_DURATION INT,
APPEARED_FOR_TEST ENUM('0','1'),
OTHER_TECHNOLGOIES VARCHAR(255),
APPLIED_ROLE VARCHAR(100),
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE IF NOT EXISTS TECHNOLOGIES(
TECH_ID INT PRIMARY KEY,
TECH_NAME VARCHAR(100) NOT NULL
); 

CREATE TABLE IF NOT EXISTS USER_TECHNOLOGIES(
USER_ID INT,
TECH_ID INT,
PRIMARY KEY (USER_ID, TECH_ID),
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
FOREIGN KEY (TECH_ID) REFERENCES TECHNOLOGIES(TECH_ID)
);

CREATE TABLE IF NOT EXISTS FRAMEWORKS(
FRAMEWORK_ID INT PRIMARY KEY,
FRAMEWORK_NAME VARCHAR(100) NOT NULL
); 

CREATE TABLE IF NOT EXISTS USER_FRAMEWORKS(
USER_ID INT,
FRAMEWORK_ID INT,
PRIMARY KEY (USER_ID, FRAMEWORK_ID),
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
FOREIGN KEY (FRAMEWORK_ID) REFERENCES FRAMEWORKS(FRAMEWORK_ID)
);

CREATE TABLE IF NOT EXISTS WALK_IN(
WALK_IN_ID INT PRIMARY KEY,
WALK_IN_START_DATE DATE,
WALK_IN_END_DATE DATE,
WALK_IN_LOCATION VARCHAR(255),
GENERAL_INSTRUCTIONS TEXT,
EXAM_INSTRUCTIONS TEXT,
MIN_SYSTEM_REQUIREMENT TEXT,
PROCESS_FLOW TEXT,
VENUE TEXT,
THINGS_TO_REMEMBER TEXT
);

CREATE TABLE IF NOT EXISTS WALK_IN_FLAG(
FLAG_ID INT AUTO_INCREMENT PRIMARY KEY,
WALK_IN_ID INT,
FLAG_DESC VARCHAR(100),
UNIQUE (WALK_IN_ID,FLAG_DESC),
FOREIGN KEY (WALK_IN_ID) REFERENCES WALK_IN(WALK_IN_ID)
);

CREATE TABLE IF NOT EXISTS WALK_IN_JOB_ROLES(
WALK_IN_ID INT,
ROLE_ID INT,
GROSS_COMPENSATION INT,
ROLE_DESCRIPTION TEXT,
REQUIREMENTS TEXT,
PRIMARY KEY (WALK_IN_ID,ROLE_ID),
FOREIGN KEY (WALK_IN_ID) REFERENCES WALK_IN(WALK_IN_ID),
FOREIGN KEY (ROLE_ID) REFERENCES JOB_ROLES(ROLE_ID)
);

CREATE TABLE IF NOT EXISTS TIME_SLOT (
    TIME_SLOT_ID INT AUTO_INCREMENT PRIMARY KEY,
    WALK_IN_ID INT,
    START_TIME TIME,
    END_TIME TIME,
    FOREIGN KEY (WALK_IN_ID) REFERENCES WALK_IN(WALK_IN_ID),
    UNIQUE (WALK_IN_ID, START_TIME, END_TIME)
);


CREATE TABLE USER_WALK_IN(
USER_ID INT,
WALK_IN_ID INT,
TIME_SLOT_ID INT,
UPDATED_RESUME VARCHAR(100),
PRIMARY KEY (USER_ID,WALK_IN_ID,TIME_SLOT_ID),
FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
FOREIGN KEY (WALK_IN_ID) REFERENCES WALK_IN(WALK_IN_ID),
FOREIGN KEY (TIME_SLOT_ID) REFERENCES TIME_SLOT(TIME_SLOT_ID)
);
	
CREATE TABLE IF NOT EXISTS USER_WALK_IN_JOB_ROLES(
USER_ID INT,
WALK_IN_ID INT,
ROLE_ID INT,
PRIMARY KEY (USER_ID,WALK_IN_ID,ROLE_ID),
FOREIGN KEY (WALK_IN_ID) REFERENCES WALK_IN(WALK_IN_ID),
FOREIGN KEY (ROLE_ID) REFERENCES JOB_ROLES(ROLE_ID)
);

